{{- if and .Values.omni.serviceAccountKey.value (not .Values.omni.serviceAccountKey.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-exporter.fullname" . }}
  labels:
    {{- include "omni-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  OMNI_SERVICE_ACCOUNT_KEY: {{ .Values.omni.serviceAccountKey.value | quote }}
{{- end }}
{{- if and .Values.webConfig.enabled .Values.webConfig.content (not .Values.webConfig.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-web-config" (include "omni-exporter.fullname" .) }}
  labels:
    {{- include "omni-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  web-config.yml: |
    {{- .Values.webConfig.content | nindent 4 }}
{{- end }}
